### ISSUE TITLE
Deceptive site ahead

### ISSUE THREAD

**Issue by mihha** [AntonioErdeljac/next-netflix-tutorial#1]
I tried to see the demo on the URL you provided but this is what I get

![image](https://user-images.githubusercontent.com/3791124/221570328-7e88f4c7-4cab-46f3-b4ac-85c7e4d9614c.png)

**Comment by Zeerti** [comment]
You can click the link that says "visit this unsafe site" to go to it regardless of the warning. 

This needs to be changed to something similar but different from Netflix. As the point of this project is to mirror Netflix as much as possible, this might be a problem forever.

**Comment by AntonioErdeljac** [comment]
Yeah, i noticed this and got a community guideline warning on youtube for sharing this link. I will try to modify the name of the site and logo to see if that helps. Thanks for reporting!
