### ISSUE TITLE
Testing login?

### ISSUE THREAD

**Issue by bornagainpenguin** [AntonioErdeljac/next-netflix-tutorial#2]
As it stands now there is no real method of testing the demo since it requires a login and non is provided.  (Did I miss it?  In that case I apologize, but I'm not seeing it.)

**Comment by Zeerti** [comment]
click the "Create an account" text and make some fake login info. Then login with said info. @bornagainpenguin

**Comment by AntonioErdeljac** [comment]
as @Zeerti said, you can create an account using "Create an account" option first

**Comment by MincePie** [comment]
I'm trying to make an account to test this but also get "AxiosError: Request failed with status code 400\n
