### ISSUE TITLE
Property 'user' does not exist on type 'typeof PrismaClient'.ts(2339)

### ISSUE THREAD

**Issue by anthonyiu** [AntonioErdeljac/next-netflix-tutorial#6]
Hi all,

I encountered this typescript issue in the following line of [...nextauth].ts file. Any clue? 
Tried googled it but couldn't find any solution. 

` const user = await prismadb.user.findUnique({
          where: { email: credentials.email },
        });`

user was underline by VS Code with the following error message: 

`Property 'user' does not exist on type 'typeof PrismaClient'.ts(2339)`

**Comment by HanikJain** [comment]
Hey [anthonyiu](https://github.com/anthonyiu),
I encountered a similar problem when deploying my application, but I resolved it by modifying the code in the `/libs/prismadb.ts` file.
## Before 
`const client = global.prismadb || new PrismaClient()`
`if (process.env.NODE_ENV !== 'production') global.prismadb = client
`
## After 
`const client =  new PrismaClient()
`

**Comment by anthonyiu** [comment]
> Hey [anthonyiu](https://github.com/anthonyiu), I encountered a similar problem when deploying my application, but I resolved it by modifying the code in the `/libs/prismadb.ts` file.
> 
> ## Before
> `const client = global.prismadb || new PrismaClient()` `if (process.env.NODE_ENV !== 'production') global.prismadb = client `
> 
> ## After
> `const client = new PrismaClient() `

Thanks @HanikJain 
My fix is a bit different from yours. It's actually my typo in `global.d.ts` when I declare the type for PrismaClient(). I should use `"` instead of `=` after `prismadb`

`import type { PrismaClient } from "@prisma/client";`
`declare global {
  namespace globalThis {
    var prismadb: PrismaClient;
  }
}
`
