### ISSUE TITLE
Can't remove favorite movie [solved]

### ISSUE THREAD

**Issue by baranero** [AntonioErdeljac/next-netflix-tutorial#7]
The problem was the incompatibility of the latest dependencies with older versions. The solution is to use package.json and package-lock.json from the repository and reinstall with 'npm i' .

**Comment by zaidtahirbutt** [comment]
Hi,

Thanks this worked for me.

**Comment by SiAce** [comment]
Jesus thank you! I have been debugging for hours for this. Anyone knows the root cause?

**Comment by Op-Pautu** [comment]
> Jesus thank you! I have been debugging for hours for this. Anyone knows the root cause?

https://github.com/AntonioErdeljac/next-netflix-tutorial/issues/14

it was referenced here
